// Driver-guides. Every EurAsia tour is run by one of these people — the guide is
// the product, so travellers pick theirs the same way they pick the vehicle.
// `image` is optional: drop a photo in src/assets/images and import it here.
// Without one the card falls back to a monogram, which looks deliberate.

export const guides = [
  {
    id: 'g-jmv',
    name: 'Jean de Dieu Habimana',
    short: 'Jean de Dieu',
    initials: 'JD',
    base: 'Musanze',
    years: 11,
    rating: 5.0,
    trips: 480,
    dayRate: 60,
    languages: ['Kinyarwanda', 'English', 'French'],
    specialities: ['wildlife', 'trekking'],
    certifications: ['RDB licensed guide', 'Wilderness first aid'],
    bio: 'Grew up in Kinigi in sight of the park gate and has tracked in the Virungas since 2015. Reads the weather on Bisoke better than the forecast does.',
  },
  {
    id: 'g-clarisse',
    name: 'Clarisse Uwase',
    short: 'Clarisse',
    initials: 'CU',
    base: 'Kigali',
    years: 8,
    rating: 4.9,
    trips: 350,
    dayRate: 55,
    languages: ['Kinyarwanda', 'English', 'French', 'Swahili'],
    specialities: ['culture', 'food'],
    certifications: ['RDB licensed guide', 'Kigali Genocide Memorial accredited'],
    bio: 'Historian by training. Runs the heritage day and will let a silence sit rather than fill it, which is the whole skill at Gisozi.',
  },
  {
    id: 'g-eric',
    name: 'Eric Nkurunziza',
    short: 'Eric',
    initials: 'EN',
    base: 'Kayonza',
    years: 13,
    rating: 4.9,
    trips: 610,
    dayRate: 65,
    languages: ['Kinyarwanda', 'English', 'Swahili', 'German'],
    specialities: ['wildlife'],
    certifications: ['RDB licensed guide', 'Advanced 4x4 recovery', 'Bird guide level II'],
    bio: 'Twelve seasons in Akagera. Knows which pride is denning where this month and will say so plainly when the answer is that nobody has seen them all week.',
  },
  {
    id: 'g-solange',
    name: 'Solange Mukamana',
    short: 'Solange',
    initials: 'SM',
    base: 'Rubavu',
    years: 6,
    rating: 4.8,
    trips: 220,
    dayRate: 50,
    languages: ['Kinyarwanda', 'English', 'French'],
    specialities: ['lake', 'food'],
    certifications: ['RDB licensed guide', 'Q-grader, coffee'],
    bio: 'Certified coffee cupper who runs the Kivu trail. If you want to understand why Rwandan coffee tastes the way it does, ask her about altitude.',
  },
  {
    id: 'g-patrick',
    name: 'Patrick Rwigema',
    short: 'Patrick',
    initials: 'PR',
    base: 'Huye',
    years: 9,
    rating: 4.8,
    trips: 300,
    dayRate: 55,
    languages: ['Kinyarwanda', 'English', 'French', 'Mandarin'],
    specialities: ['trekking', 'culture'],
    certifications: ['RDB licensed guide', 'Nyungwe forest ecology'],
    bio: 'Spent four years with a forestry programme in Nyungwe before guiding. Can name most of what you walk past, and will if you ask.',
  },
  {
    id: 'g-aline',
    name: 'Aline Ingabire',
    short: 'Aline',
    initials: 'AI',
    base: 'Kigali',
    years: 5,
    rating: 4.9,
    trips: 190,
    dayRate: 50,
    languages: ['Kinyarwanda', 'English', 'Swahili'],
    specialities: ['culture', 'lake'],
    certifications: ['RDB licensed guide', 'First aid'],
    bio: 'Came to guiding from hospitality and it shows in the logistics. Nothing on her itineraries runs late.',
  },
];

export const LANGUAGE_FILTERS = ['English', 'French', 'Swahili', 'German', 'Mandarin', 'Kinyarwanda'];
